import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { LoadModelComponent } from '@/components/LoadModelComponent'
import { StageComponent } from '@/components/StageComponent'
import { useCallback, useEffect, useState } from 'react'
import { VRM } from '@pixiv/three-vrm'
import { setFile, receive } from '@/libs/TransitionProtocol'
import { userVRMLoadAsync } from '@/libs/VRMControlSystem'

/**
 * サイトのホーム
 * @returns indexの見た目を返す
 */
export default function Home() {
  
  // プレイヤーのVRMモデル
  const [model, setModel] = useState<VRM>()

  // 最初に一回実行
  useEffect(() => {
    receive(new URL(window.location.href))
      .then((model) => {
        console.log(model)
        setFile(model.item)
        .then(async () => { return await userVRMLoadAsync(model.item) })
        .then((vrm) => {
          setModel(vrm)
          window.history.pushState(null, '', '/')
        })
      })
  }, [])

  // インプットから読み込む処理
  const loadScene = useCallback(() => {
    if (model) return <StageComponent vrm={model} />
    else return <LoadModelComponent onFileLoad={(vrm) => { setModel(vrm) }}/>
  }, [model])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        { loadScene() }
      </main>
    </>
  )
}
