import Head from 'next/head'
import { send } from '@/libs/TransitionProtocol'
import { useEffect } from 'react'

/**
 * 遷移用ページ(iFrameの中に埋めこむ)
 * @returns TransitionページのHTML返す
 */
export default function Transition() {

  // 親にVRMを送る
  useEffect(() => {
    // NOTE: Originが*になっているのは危険なので本来は適切なOriginに設定する
    send('*')
  }, [])

  // UIに特に意味はないがUIを返す
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>transition</h1>
      </main>
    </>
  )
}
